### ISSUE TITLE
Install your plugin in drupal 8

### ISSUE THREAD

**Issue by phoretis** [thomasmars/h5p-add-source#1]
Hi,

Thanks for your job and this plugin already old (3 years)
I try to add some buttons (table, img, color and source) so i try your plugin in drupal 8 (i just make some little modifications to make it working with adding h5p_add_source.info.yml. I can activate it but it's not working... any help, idea ?
By the way i don't understand why there is not the ability in admin configuration of h5p to add needed button in the tollbar (with security information).
Personaly i use a lot "fill in the blank" why the color button has been removed ?

Regards

**Comment by thomasmars** [comment]
Hi, I don't plan to add any features or make the plugin compatible with Drupal 8 if it is not, since I don't use this myself.
Feel free to fork the project and make changes.
The reason why there's not a lot of option in CKEditor in H5P is that we've tried to keep the options limited, and they can be overridden if users need more functionality. Also this has not been a requested feature, so it just hasn't been prioritized.
